version: '3.7'
services:
  rest-api:
    container_name: rest-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_CONNSTRING=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongodb/${MONGO_DB_NAME}
    build:
        context: ./ 

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongodb-service
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}

  caddy:
    image: caddy/caddy:2.6.2-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - $PWD/Caddyfile:/etc/caddy/Caddyfile
    - $PWD/site:/srv
    - caddy_data:/data
    - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: